track_ml:
    dir: /global/cscratch1/sd/xju/heptrkx/codalab_inputs/train_all
    detector: /global/cscratch1/sd/xju/heptrkx/codalab_inputs/detector.csv

true_hits:
    dir: /global/cscratch1/sd/xju/heptrkx/pairs/true_pairs_moreVars3

doublets_for_training:
    base_dir: /global/cscratch1/sd/xju/heptrkx/pairs
    true_pairs: merged_true_pairs # only true pairs
    all_pairs: all_pairs_moreVars # all pairs, used for training, testing, for Graph

doublet_training:
    batch_size: 512
    epochs: 6
    eff_cut: 0.98
    model_output_dir: /global/cscratch1/sd/xju/heptrkx/trained_models/doublet_moreVar
    features: ['x_in', 'x_out', 'y_in', 'y_out', 'z_in', 'z_out', 'lx_in', 'lx_out', 'ly_in', 'ly_out', 'lz_in', 'lz_out']
    bkg_from_evtid: 6600

doublets_for_graph: ## input pairs from all_pairs
    evtid: 1000
    selected: /global/cscratch1/sd/xju/heptrkx/output_graphs_moreVar2/selected_pairs
    layers: [7, 8, 9, 10, 24, 25, 26, 27, 40, 41]
    min_hits: 3
    threshold: /global/cscratch1/sd/xju/heptrkx/trained_models/doublet_moreVar/merged_info.txt 

make_graph:
    nevts: 10
    out_graph: /global/cscratch1/sd/xju/heptrkx/output_graphs_moreVar2/barrel_graphs_hdf5
    pairs_from: 'doublets_from_cuts'

doublets_from_cuts:
    evtid: 21001
    selected: /global/cscratch1/sd/xju/heptrkx/codalab_outputs/selected_pairs_from_cuts_HDF5_noDup
    layers: [7, 8, 9, 10, 24, 25, 26, 27, 40, 41]
    min_hits: 3
    phi_slope_max: 0.0006
    z0_max: 100

segment_training:
    output_dir: /global/cscratch1/sd/xju/heptrkx/trained_models/segments
    model_name: VARY
    prod_name: barrel_NNs_10
    log_name: big.log
    input_type: 'data_dict'
    parameters:
        time_lapse:  240 # how often save checkpoint in seconds
        batch_size: 1
        iterations: 8000
        iter_per_job: 8000
        n_iters: 8
        learning_rate: 0.01
        real_weight: 1.0
        fake_weight: 0.5


