prod_name: nxgraph_big_morelayers_001
output_dir: /global/homes/x/xju/track/gnn/code/gnn_networkx/trained_results
data:
    name: hitgraphs
    input_dir: /global/cscratch1/sd/xju/heptrkx/data/hitgraphs_big_000
    section: 0

model:
    name: default

train:
    log_name: big_new_edge_features.log
    time_lapse:  120  # how often save checkpoint in seconds
    batch_size: 2
    iterations: 30000
    iter_per_job: 2000
    n_iters: 8
    learning_rate: 0.001
