prod_name: nxgraph_pairs_004
output_dir: /global/homes/x/xju/track/gnn/code/gnn_networkx/trained_results
data:
    name: hitgraphs
    input_hitsgraph_dir: /global/cscratch1/sd/xju/heptrkx/data/hitgraphs_big_000
    output_nxgraph_dir:  /global/cscratch1/sd/xju/heptrkx/data/graphs_from_pairs_phi4_eta6
    log_name: data_process.log

model:
    name: default

train:
    log_name: big.log
    time_lapse:  30 # how often save checkpoint in seconds
    batch_size: 1
    iterations: 180000
    iter_per_job: 20000
    n_iters: 8
    learning_rate: 0.001
    real_weight: 1.5
    fake_weight: 0.5
