prod_name: nxgraph_small_decoder_001
output_dir: /global/homes/x/xju/track/gnn/code/gnn_networkx/trained_results
data:
    name: hitgraphs
    input_dir: /global/cscratch1/sd/xju/heptrkx/data/hitgraphs_001
    section: 0

model:
    name: default

train:
    log_name: train_nx_graph_decoder.log
    time_lapse:  240  # how often save checkpoint in seconds
    batch_size: 2
    iterations: 30000
    n_iters: 4
    learning_rate: 0.001

