prod_name: nxgraph_big_007
output_dir: /global/homes/x/xju/track/gnn/code/gnn_networkx/trained_results
data:
    name: hitgraphs
    input_hitsgraph_dir: /global/homes/x/xju/atlas/heptrkx/data/hitgraphs_big_000
    output_nxgraph_dir: /global/homes/x/xju/work/heptrkx/trackml/outputs/nxgraphs_big_001
    input_evt_dir: /global/homes/x/xju/atlas/heptrkx/trackml_inputs/train_all
    blacklist_dir: /global/homes/x/xju/atlas/heptrkx/trackml_inputs/blacklist
    log_name: data_process.log
    n_tasks: 1
    n_workers: 32

model:
    name: default

train:
    log_name: big.log
    time_lapse:  120 # how often save checkpoint in seconds
    batch_size: 4
    iterations: 270000
    iter_per_job: 20000
    n_iters: 8
    learning_rate: 0.0001
    real_weight: 1.0
    fake_weight: 0.5
