prod_name: nxgraph_pairs_4evts
output_dir: /global/homes/x/xju/track/gnn/code/gnn_networkx/trained_results
data:
    name: hitgraphs
    input_hitsgraph_dir: /global/cscratch1/sd/xju/heptrkx/data/
    output_nxgraph_dir:  /global/cscratch1/sd/xju/heptrkx/data/graph_from_pairs_test
    log_name: data_process.log

model:
    name: default

train:
    log_name: pairs.log
    time_lapse:  120 # how often save checkpoint in seconds
    batch_size: 2
    iterations: 30000
    iter_per_job: 5000
    n_iters: 10
    learning_rate: 0.001
