input_pairs: /global/homes/x/xju/track/gnn/code/top-quarks/trained/output_pairs_100
input_track_events: /global/homes/x/xju/atlas/heptrkx/trackml_inputs/train_100_events
output_graphs: /global/homes/x/xju/atlas/heptrkx/data/graphs_from_pairs_phi4_eta6
n_workers: 37
start_jobID: 64
n_phi_sections: 4
n_eta_sections: 6    # for reference, don't change
eta_edges: [-5, -0.75, -0.35, 0, 0.35, 0.75, 5] # for reference, don't change
