output_dir: ${SCRATCH}/heptrkx/results/gnn_hitgraphs001_test_distributed

data:
    name: hitgraphs
    input_dir: ${SCRATCH}/heptrkx/data/hitgraphs_001
    n_train: 1000
    n_valid: 500
    batch_size: 2
    n_workers: 4

experiment:
    name: gnn
    output_dir: /global/homes/x/xju/track/gnn/code/heptrkx-gnn-tracking/test_distributed_001

trainer:
    name: gnn
    real_weight: 5.0   # 0.5 / 0.1
    fake_weight: 0.555 # 0.5 / 0.9

training:
    n_epochs: 20

model:
    name: 'gnn_segment_classifier'
    input_dim: 3
    hidden_dim: 128
    n_iters: 6
    loss_func: 'binary_cross_entropy'
    optimizer: 'Adam'
    learning_rate: 0.001
